package com.sanjeev.stephan.murmu.kotlincodes

val myListArray = arrayOf(
    "Android APIs",
    "Android LifeCycle",
    "Android EditText and TextView",
    "Access Call,Dialer,Camera & WebPage",
    "AdMob Banner Ads",
    "AdMob Interstitial Ads",
    "App Chooser",
    "Button",
    "Bottom-Sheet",
    "CardView",
    "Check Device-Orientation",
    "Change Screen-Orientation",
    "Check Internet Connectivity",
    "Dialog Alert",
    "Dialog Input",
    "Dialog Confirmation",
    "Dialog Progress",
    "Fragment",
    "Floating Text",
    "Firebase",
    "File Handler - Read and Write Text",
    "Gesture",
    "Intent Explicit",
    "Intent Implicit",
    "JSON Parsing using URL",
    "Linkify",
    "ListView",
    "ListView Custom",
    "List SdCard Directories",
    "Map Fixed Location",
    "Map Current Location",
    "Make and Delete Directory",
    "Notification",
    "Option Menu",
    "Picker Data & Timer",
    "Popup Menu",
    "Player Audio",
    "Player Video",
    "Remove Action-Bar",
    "Read Text From Assets",
    "RecyclerView",
    "Sharing Intent using App Package",
    "Shared Preferences",
    "Start New Activity",
    "SearchView with Text-Filter",
    "Spinner",
    "SnackBar",
    "Secret Developer Option",
    "SQLite Database",
    "Storage Internal",
    "Storage External",
    "Select Image From Gallery",
    "TextClock",
    "Text-Change Listener",
    "Timer",
    "Toast",
    "Toast Custom",
    "TabLayout with FrameLayout",
    "TabLayout with ViewPager",
    "Vibrator",
    "WebView",
    "Web Services",
    "WiFi Manager",
    "XMLPullParser"

)